print ("Wellcome to polectron's easy G-code splitting tool")

gcodeFile = raw_input("G-code filename: ")
beginning = float(raw_input("First layer height in mm (0 for first layer): "))
end = float(raw_input("Last layer height in mm (-1 for last layer): "))

fileData = open(gcodeFile)
gcodeLines = fileData.read().split("\n")

prologue = True
inRange = False

destinyFile = open(gcodeFile.rstrip(".gcode") + "_splitted.gcode", "w")

lastGCode = 0

pos = 0
for line in gcodeLines:
    data = line.split(";")[0]
    data = data.split(" ")
    if data[0] == "G1":
        lastGCode = pos
    pos += 1

print("Last position G-code is in line {0}".format(lastGCode))

def hasZAxis(data):
    for piece in data:
        if "Z" in piece:
            return True
    return False

def getZAxis(data):
    zpos = 0
    for piece in data:
        if "Z" in piece:
            return float(piece.lstrip("Z")), zpos
        zpos += 1

pos = 0
for line in gcodeLines:
    data = line.split(";")[0]
    data = data.split(" ")
    if(pos > lastGCode):
        inRange = False
        print("Reached end of usable G-code")
        break
    if(len(line) > 0):
        if(line[0] != ";"):
            if(data[0] == "G1" and "Z0" in line):
                if prologue:
                    print("End of prologue reached, starting the spliting")
                    prologue = False

            if prologue:
                destinyFile.write(line + "\n")
            else:
                if(data[0] == "G1"):
                    if(hasZAxis(data)):
                        zAxis, zpos = getZAxis(data)
                        if(zAxis >= beginning and (zAxis <= end or end == -1.0)):
                            inRange = True
                        elif(zAxis > end and end != -1.0):
                            inRange = False
                            print("Reached end of range")
                            break
                        else:
                            inRange = False

                        if(inRange):
                            data[zpos] = "Z{0}".format(zAxis - beginning)
                            destinyFile.write(" ".join(data) + "\n")
                    else:
                        if(inRange):
                            destinyFile.write(line + "\n")
                else:
                    if(inRange):
                        destinyFile.write(line + "\n")
    pos += 1

print("Splitting finished")

print("Introducing epilogue")

destinyFile.write("M104 S0 ; turn off temperature\n")
destinyFile.write("M140 S0; turn off bed\n")

destinyFile.write("M300 S1800 P200 ;Finish beep\n")

destinyFile.write("G28 X0  ; home X axis\n")
destinyFile.write("G1 X4 Y190 F1200 ; lift nozzle to output print (Z 100 removed to save time)\n")
destinyFile.write("M84     ; disable motors\n")
destinyFile.write("M116 ; wait for cooling down\n")
destinyFile.write("M107 ;Turn off nozzle fan\n")


destinyFile.write("; End of splitting\n")
destinyFile.write("; Split generated by polectron's splitting tool\n")
destinyFile.close()

print("File successfully saved")
